### ISSUE TITLE
How can i get from your repo the daily picoD0 file?

### ISSUE THREAD

**Issue by MustafaMustafa** [MustafaMustafa/auau200GeVRun14#17]
Hi Mustafa,

  How can i get from your repo the daily picoD0 file. I did

git pull origin master

but it gives an error that since i made changes to StPicoD0AnaMaker it
aborts and does not merge. Also the picoD0 daily file list i cannot copy

I am sure i am doing something wrong but can you suggest

Anju,

**Comment by MustafaMustafa** [comment]
Hi, Anju, 

I am sorry about that. Can you please share the error message and your directory location to see your setup?

**Comment by anjubhasin** [comment]
Hi Mustafa,
My directory location is /global/homes/a/abhasin/mustafa_code/auau200GeVRun14
the error is below

anju

>git pull origin master
From https://github.com/MustafaMustafa/auau200GeVRun14
 * branch            master     -> FETCH_HEAD
Updating 91188b2..19f1830
error: Your local changes to 'StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.

**Comment by MustafaMustafa** [comment]
Hi, Anju, 

This is because Jochen updated the D0AnaMaker last night. We are working on a strategy to avoid having this problem in the future especially that people need new D0 production lists daily. 

For the moment, I suggest you first commit your local changes and then follow the steps mentioned in this page http://nbviewer.ipython.org/gist/choldgraf/6359961
to the do a partial merge. 

Let me know if this works out for you and thank you for reporting :-)

**Comment by anjubhasin** [comment]
yes it works now . Thanks

**Comment by MustafaMustafa** [comment]
Thank you for reporting.
