### ISSUE TITLE
Error loading pico list

### ISSUE THREAD

**Issue by aaqs01** [MustafaMustafa/auau200GeVRun14#18]
I am following the instructions on slide 9 of Mustafa's presentation on HF pwg April/2/21015 but I am having and error after loading a picoDst.list:

...
StInfo: StPicoD0AnaMaker - Adding :/project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics/P15ic/166/15166010/st_physics_15166010_raw_0000013.picoDst.root
StInfo: StPicoD0AnaMaker - Adding :/project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics/P15ic/166/15166010/st_physics_15166010_raw_1000002.picoDst.root
StInfo: StPicoD0AnaMaker - Adding :/project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics/P15ic/166/15166010/st_physics_15166010_raw_1000012.picoDst.root
Error in <TChain::LoadTree>: Cannot find tree with name T in file /project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics/P15ic/166/15166010/st_physics_15166010_raw_0000013.picoDst.root
Error in <TChain::LoadTree>: Cannot find tree with name T in file /project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics/P15ic/166/15166010/st_physics_15166010_raw_1000002.picoDst.root
Error in <TChain::LoadTree>: Cannot find tree with name T in file /project/projectdirs/starprod/picodsts/Run14/AuAu/200GeV/physics/P15ic/166/15166010/st_physics_15166010_raw_1000012.picoDst.root

 *** Break *** segmentation violation
Root > Function runPicoD0AnaMaker() busy flag cleared

**Comment by MustafaMustafa** [comment]
Hi, Amilkar, 

You are trying to pass a list of PicoDst files to the macro that reads D0 trees. You need to pass a list of D0 trees as shown in the tutorial slides. 

You can find lists of D0 trees under:
/global/homes/a/aquinter/PicoDst/auau200GeVRun14/fileLists/picoD0Lists/daily
